version: '3.7'

services:
  postgres:
    image: 'postgres:16.2'

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=Postgres01
      - POSTGRES_USER=postgres
      - TZ=Europe/Kiev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #      - postgres_logs:/var/log/postgresql
#    command:
#            -c logging_collector=on
#            -c log_directory=/var/log/postgresql
#            -c log_filename=postgresql-%Y-%m-%d_%H%M%S.log
#            -c log_min_error_statement=error
#            -c log_autovacuum_min_duration=0
#
#    #      -c shared_preload_libraries='promscale_extension'
#    #      -c shared_preload_libraries='pg_stat_statements'
#    #      -c pg_stat_statements.track=all
#    #      -c shared_preload_libraries='timescaledb'
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
volumes:
  postgres_data:
#  postgres_logs:

networks:
  monitoring:


#docker-compose up -build
#docker-compose up -d

# psql -U postgres -d prometheus
# \dx
#CREATE EXTENSION IF NOT EXISTS pg_prometheus;